<?php

/**
 * This is the model base class for the table "VComUPIAggregationRuleStart".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VComUPIAggregationRuleStart".
 *
 * Columns in table "VComUPIAggregationRuleStart" available as properties of the model,
 * followed by relations of table "VComUPIAggregationRuleStart" available as properties of the model.
 *
 * @property integer $id
 * @property integer $vcomuserrole
 * @property integer $upiaggregationrulestart
 * @property integer $allowedRead
 * @property integer $allowedWrite
 *
 * @property UPIAggregationRuleStart $upiaggregationrulestart0
 * @property VComUserRole $vcomuserrole0
 */
abstract class BaseVComUPIAggregationRuleStart extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'VComUPIAggregationRuleStart';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Papel X Regra de Publicação|Papeis X Regras de Publicações', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('vcomuserrole, upiaggregationrulestart', 'required'),
			array('vcomuserrole, upiaggregationrulestart, allowedRead, allowedWrite', 'numerical', 'integerOnly'=>true),
			array('allowedRead, allowedWrite', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, vcomuserrole, upiaggregationrulestart, allowedRead, allowedWrite', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'upiaggregationrulestart0' => array(self::BELONGS_TO, 'UPIAggregationRuleStart', 'upiaggregationrulestart'),
			'vcomuserrole0' => array(self::BELONGS_TO, 'VComUserRole', 'vcomuserrole'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
                        'id' => Yii::t('app', 'ID'),
                        'vcomuserrole' => Yii::t('app', 'Papel do usuário'),
                        'upiaggregationrulestart' => Yii::t('app', 'Regra de criação de publicações'),
                        'allowedRead' => Yii::t('app', 'Visualizará publicações criada pela regra'),
                        'allowedWrite' => Yii::t('app', 'Criará publicações pela regra'),                    
                        /*
			'id' => Yii::t('app', 'ID'),
			'vcomuserrole' => null,
			'upiaggregationrulestart' => null,
			'allowedRead' => Yii::t('app', 'Allowed Read'),
			'allowedWrite' => Yii::t('app', 'Allowed Write'),
                         */
			'upiaggregationrulestart0' => Yii::t('app', 'Regra de criação de publicações associadas'),
			'vcomuserrole0' => Yii::t('app', 'Papeis de usuários'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('vcomuserrole', $this->vcomuserrole);
		$criteria->compare('upiaggregationrulestart', $this->upiaggregationrulestart);
		$criteria->compare('allowedRead', $this->allowedRead);
		$criteria->compare('allowedWrite', $this->allowedWrite);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}