<?php

/**
 * This is the model base class for the table "ExemploYii".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExemploYii".
 *
 * Columns in table "ExemploYii" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $Nome
 * @property string $Descrição
 *
 */
abstract class BaseExemploYii extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ExemploYii';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ExemploYii|ExemploYiis', $n);
	}

	public static function representingColumn() {
		return 'Nome';
	}

	public function rules() {
		return array(
			array('Nome, Descrição', 'required'),
			array('Nome', 'length', 'max'=>100),
			array('id, Nome, Descrição', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'Nome' => Yii::t('app', 'Nome'),
			'Descrição' => Yii::t('app', 'Descrição'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('Nome', $this->Nome, true);
		$criteria->compare('Descrição', $this->Descrição, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}