<?php

/**
 * This is the model base class for the table "UserVComUserRole".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserVComUserRole".
 *
 * Columns in table "UserVComUserRole" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user
 * @property integer $vcomuserrole
 *
 */
abstract class BaseUserVComUserRole extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'UserVComUserRole';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserVComUserRole|UserVComUserRoles', $n);
	}

	public static function representingColumn() {
		return array(
			'user',
			'vcomuserrole',
		);
	}

	public function rules() {
		return array(
			array('user, vcomuserrole', 'required'),
			array('user, vcomuserrole', 'numerical', 'integerOnly'=>true),
			array('user, vcomuserrole', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user' => Yii::t('app', 'Usuário'),
			'vcomuserrole' => Yii::t('app', 'Papel de Usuário'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user', $this->user);
		$criteria->compare('vcomuserrole', $this->vcomuserrole);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}