<?php

/**
 * This is the model base class for the table "VComUPIAggregationRuleResponseOf".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VComUPIAggregationRuleResponseOf".
 *
 * Columns in table "VComUPIAggregationRuleResponseOf" available as properties of the model,
 * followed by relations of table "VComUPIAggregationRuleResponseOf" available as properties of the model.
 *
 * @property integer $id
 * @property integer $vcomuserole
 * @property integer $upiaggregationruleresponseof
 * @property integer $allowedRead
 * @property integer $allowedWrite
 *
 * @property UPIAggregationRuleResponseOf $upiaggregationruleresponseof0
 * @property VComUserRole $vcomuserole0
 */
abstract class BaseVComUPIAggregationRuleResponseOf extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'VComUPIAggregationRuleResponseOf';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Papel X Regra de Resposta|Papeis X Regras de Respostas', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('vcomuserole, upiaggregationruleresponseof', 'required'),
			array('vcomuserole, upiaggregationruleresponseof, allowedRead, allowedWrite', 'numerical', 'integerOnly'=>true),
			array('allowedRead, allowedWrite', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, vcomuserole, upiaggregationruleresponseof, allowedRead, allowedWrite', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'upiaggregationruleresponseof0' => array(self::BELONGS_TO, 'UPIAggregationRuleResponseOf', 'upiaggregationruleresponseof'),
			'vcomuserole0' => array(self::BELONGS_TO, 'VComUserRole', 'vcomuserole'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'vcomuserole' => Yii::t('app', 'Papel de Usuário'),
			'upiaggregationruleresponseof' => Yii::t('app', 'Regras de Resposta'),
                        'allowedRead' => Yii::t('app', 'Visualizará publicações criada pela regra'),
                        'allowedWrite' => Yii::t('app', 'Criará publicações pela regra'),                             
			'upiaggregationruleresponseof0' => Yii::t('app', 'Regra de respostas'),
			'vcomuserrole0' => Yii::t('app', 'Papeis de usuários'),                    
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('vcomuserole', $this->vcomuserole);
		$criteria->compare('upiaggregationruleresponseof', $this->upiaggregationruleresponseof);
		$criteria->compare('allowedRead', $this->allowedRead);
		$criteria->compare('allowedWrite', $this->allowedWrite);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}